@echo off
setlocal

:: Generate a timestamp
for /f "delims=" %%i in ('powershell -Command "Get-Date -Format \"yyyy-MM-dd-HHmmss\""') do set TIMESTAMP=%%i

:: Define the document and main file names
set DOCUMENT=draft-thesis-%TIMESTAMP%.pdf
set MAIN=diss

:: Build the PDF
call :buildPDF

:: Rename the output file
if exist %MAIN%.pdf (
    move %MAIN%.pdf %DOCUMENT%
) else (
    echo Failed to create %MAIN%.pdf
    goto end
)

:: Clean up auxiliary files (optional)
:: call :clean

:end
endlocal
goto :eof

:: Function to build the PDF
:buildPDF
latexmk -lualatex -C %MAIN%.tex
latexmk -lualatex %MAIN%.tex
latexmk -lualatex %MAIN%.tex
goto :eof

:: Function to clean up auxiliary files generated by LaTeX
:clean
del /Q *.aux *.log *.out *.toc
goto :eof
